use db_Pedidos
set language brazilian

-- EXERCICIO

 -- 1) TB_PEDIDO x TB_ITENSPEDIDO X TB_PRODUTO 
 -- retornar TB_PRODUTO = DESCRICAO
 -- retornar TB_PEDIDO = VLR_TOTAL
 -- formate para contábil VLR_TOTAL
 -- filtre o produto que contenha RELOGIO
 -- agrupe os valores para o produto RELOGIO
 -- 1 registro
   select 		
		PRODUTO.DESCRICAO,		
		format(sum(PEDIDO.VLR_TOTAL),'C', 'PT-BR') [VLR TOTAL]
   from TB_PEDIDO PEDIDO 
		join TB_ITENSPEDIDO ITENS
			on PEDIDO.NUM_PEDIDO = ITENS.NUM_PEDIDO	
		join TB_PRODUTO PRODUTO
			on PRODUTO.COD_PRODUTO = ITENS.COD_PRODUTO
   where PRODUTO.DESCRICAO like '%RELOGIO%'
   group by PRODUTO.DESCRICAO 


/*
 2) pede-se: 
 TB_DEPARTAMENTO x  TB_EMPREGADO X TB_CARGO
 RETORNAR: DEPARTAMENTO, NOME EMPREGADO, CARGO, SALARIO
 CALCULAR: SOMA SALARIO, MEDIA SALARIO
 AGRUPE OS DADOS
 CLASSIFIQUE POR DEPARTAMENTO
 
 58 REGISTROS
*/
SELECT 	
	DEPTO.DEPTO,
	EMPREGADO.NOME,
	CARGO.CARGO,
	SUM(EMPREGADO.SALARIO) AS [SALÁRIO],
	AVG(EMPREGADO.SALARIO) AS [MÉDIA SALARIAL]
FROM TB_DEPARTAMENTO DEPTO 
		INNER JOIN TB_EMPREGADO EMPREGADO
		 ON DEPTO.COD_DEPTO = EMPREGADO.COD_DEPTO
		INNER JOIN TB_CARGO CARGO
		 ON CARGO.COD_CARGO = EMPREGADO.COD_CARGO
GROUP BY DEPTO.DEPTO,	EMPREGADO.NOME,	CARGO.CARGO
ORDER BY DEPTO.DEPTO 


-- 3) TB_CLIENTE X TB_PEDIDO X TB_VENDEDOR
-- RETORNE OS CAMPOS: ESTADO, VLR_TOTAL, NUM_PEDIDO
-- POR [ESTADO] LOCALIZE O MAIOR [VLR_TOTAL] AS [MAIOR VALOR] 
-- FAÇA CONTAGEM DO [NUM_PEDIDO] AS [QTDE PEDIDO]
-- FAÇA O AGRUPAMENTO CORRETO
-- CLASSIFIQUE POR: [MAIOR VALOR] DESC

-- 22 REGISTROS
SELECT 	 
	 CLIENTE.ESTADO,	 
	 MAX(PEDIDO.VLR_TOTAL) AS [MAIOR VALOR],
	 COUNT(PEDIDO.NUM_PEDIDO) AS [QTDE PEDIDO]
FROM TB_CLIENTE CLIENTE 
		INNER JOIN TB_PEDIDO PEDIDO
			ON CLIENTE.CODCLI = PEDIDO.CODCLI
		INNER JOIN TB_VENDEDOR VENDEDOR
			ON VENDEDOR.CODVEN = PEDIDO.CODVEN
GROUP BY CLIENTE.ESTADO
ORDER BY  [MAIOR VALOR] DESC

